### ISSUE TITLE
"Read More" button cuts off text 

### ISSUE THREAD

**Issue by angelathe** [prabhuignoto/react-chrono#265] opened 2022-07-01 02:26 UTC
**Description**: The "Read More" button doesn't show up when the text is larger than the text container (within the border) but is smaller/the same size as the full timeline container. For example, when I make my browser (Chrome) window very narrow, the read more buttons show up, but when I reload the window with a larger width, some of the read more buttons don't show up and the containers prematurely cut off text. Attaching a screenshot video of the problem (before vs. after changing the Chrome window size). Thanks so much!

**Expected**: The Read More button should appear when text is hidden by the border of the container, even if it is the same size

https://user-images.githubusercontent.com/40042932/176811213-a4759a8e-7cfc-4d39-8541-02ece985ec07.mp4

**Comment by cc-greglorenzen** [comment] 2023-02-11 01:46
Are there any updates on this? I'm having similar issues, and for the most part, the "read more" button does not appear at all, even with useReadMore set to true.

**Comment by prabhuignoto** [comment] 2023-02-13 07:51
@cc-greglorenzen i am unable to reproduce this locally. Can you share the repo or a sandbox where this could be reproduced

**Comment by cc-greglorenzen** [comment] 2023-02-13 18:45
@prabhuignoto Sure thing. Here is a link to a demo repo: https://github.com/cc-greglorenzen/chrono-test

And here's a screenshot of what I'm seeing.
![image](https://user-images.githubusercontent.com/45016301/218546732-b5ab24d2-b488-44a7-a62b-29738ff003b4.png)

**Comment by cc-greglorenzen** [comment] 2023-02-13 18:51
After some more testing, this looks like an issue with using the timelineContent field with ReactNodes. The read more button renders OK with the cardDetailedText field.

**Comment by prabhuignoto** [comment] 2023-02-14 04:33
@cc-greglorenzen thanks for sharing the repo. i can reproduce the issue now. will release a fix for this pretty soon

**Comment by cc-greglorenzen** [comment] 2023-02-14 17:48
@prabhuignoto No problem!

**Closed** 2023-02-15 10:01 UTC
Labels: bug

**Comment by cc-greglorenzen** [comment] 2023-02-16 23:24
@prabhuignoto I installed the latest release (1.22), which fixed it for a short time, but the issue seems to be back again. I updated the test repo I previously sent if you want to take a look.

**Comment by prabhuignoto** [comment] 2023-02-17 04:11
@cc-greglorenzen can you post a screen grab of what you are seeing, so i can understand the issue quickly?

**Comment by cc-greglorenzen** [comment] 2023-02-17 19:02
@prabhuignoto Similar issue to the previous one. The Read More button does not show up when useReadMore is true.
The first image is with useReadMore set to true, and the second is with useReadMore set to false.

![image](https://user-images.githubusercontent.com/45016301/219762390-0bd87a8f-5b31-457d-bd62-2339bd804b41.png)
![image](https://user-images.githubusercontent.com/45016301/219762593-0906eb26-d3d2-4909-88ed-6ad76597db3e.png)
